package project.demo;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form InventoryFrame
     */
    public LoginPage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        LCpanel = new javax.swing.JPanel();
        LRpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LLpanel = new javax.swing.JPanel();
        LoginTitle = new javax.swing.JLabel();
        LUsername = new javax.swing.JLabel();
        tfLUsername = new javax.swing.JTextField();
        LPassword = new javax.swing.JLabel();
        tfLPassword = new javax.swing.JPasswordField();
        seePass = new javax.swing.JCheckBox();
        dontHave = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();
        btLsign = new javax.swing.JButton();
        errorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LCpanel.setBackground(new java.awt.Color(204, 204, 204));
        LCpanel.setPreferredSize(new java.awt.Dimension(800, 500));
        LCpanel.setLayout(null);

        LRpanel.setBackground(new java.awt.Color(153, 0, 153));
        LRpanel.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setFont(new java.awt.Font("Ink Free", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventory");

        jLabel3.setFont(new java.awt.Font("Ink Free", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("System");

        jLabel4.setFont(new java.awt.Font("Ink Free", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Login to the page to find your product.");

        jLabel5.setFont(new java.awt.Font("Ink Free", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("You can sort, add, update and delete your items easily.");

        jLabel2.setFont(new java.awt.Font("Ink Free", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Management");

        javax.swing.GroupLayout LRpanelLayout = new javax.swing.GroupLayout(LRpanel);
        LRpanel.setLayout(LRpanelLayout);
        LRpanelLayout.setHorizontalGroup(
                LRpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LRpanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(LRpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(50, Short.MAX_VALUE))
        );
        LRpanelLayout.setVerticalGroup(
                LRpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LRpanelLayout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addContainerGap(134, Short.MAX_VALUE))
        );

        LCpanel.add(LRpanel);
        LRpanel.setBounds(0, 0, 410, 500);

        LLpanel.setBackground(new java.awt.Color(255, 255, 255));
        LLpanel.setMinimumSize(new java.awt.Dimension(400, 500));

        LoginTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        LoginTitle.setForeground(new java.awt.Color(153, 0, 153));
        LoginTitle.setText("LOGIN");

        LUsername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LUsername.setText("Username");

        tfLUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLUsernameActionPerformed(evt);
            }
        });

        LPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LPassword.setText("Password");

        seePass.setText("show password");
        seePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePassActionPerformed(evt);
            }
        });

        dontHave.setText("Don't have an account?");

        btLogin.setBackground(new java.awt.Color(153, 0, 153));
        btLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btLogin.setForeground(new java.awt.Color(255, 255, 255));
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        btLsign.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btLsign.setForeground(new java.awt.Color(153, 0, 153));
        btLsign.setText("Sign up");
        btLsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLsignActionPerformed(evt);
            }
        });

        errorMessage.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout LLpanelLayout = new javax.swing.GroupLayout(LLpanel);
        LLpanel.setLayout(LLpanelLayout);
        LLpanelLayout.setHorizontalGroup(
                LLpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LLpanelLayout.createSequentialGroup()
                                .addGroup(LLpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(LLpanelLayout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addGroup(LLpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(LLpanelLayout.createSequentialGroup()
                                                                .addComponent(dontHave)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btLsign, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(LPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(LLpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(tfLPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(tfLUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(seePass))
                                                        .addComponent(LUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(LLpanelLayout.createSequentialGroup()
                                                                .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(errorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGroup(LLpanelLayout.createSequentialGroup()
                                                .addGap(130, 130, 130)
                                                .addComponent(LoginTitle)))
                                .addContainerGap(70, Short.MAX_VALUE))
        );
        LLpanelLayout.setVerticalGroup(
                LLpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LLpanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(LoginTitle)
                                .addGap(33, 33, 33)
                                .addComponent(LUsername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfLUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LPassword)
                                .addGap(18, 18, 18)
                                .addComponent(tfLPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seePass)
                                .addGap(13, 13, 13)
                                .addGroup(LLpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(errorMessage))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addGroup(LLpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dontHave)
                                        .addComponent(btLsign, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))
        );

        LCpanel.add(LLpanel);
        LLpanel.setBounds(410, 0, 390, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LCpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LCpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void tfLUsernameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    private void btLsignActionPerformed(java.awt.event.ActionEvent evt) {
        SignUpPage signIn = new SignUpPage();
        signIn.setLocationRelativeTo(null);
        signIn.setVisible(true);
        dispose();

    }

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {
        String username = tfLUsername.getText();
        String password = new String(tfLPassword.getPassword());
        boolean isValid = checkLoginCredentials(username, password);
        if (isValid) {
            InventoryPage main = new InventoryPage();
            main.setLocationRelativeTo(null);
            main.setVisible(true);
            dispose();
        } else {
            errorMessage.setText("Invalid username or password.");
        }

    }

    private void seePassActionPerformed(java.awt.event.ActionEvent evt) {

        JCheckBox checkBox = (JCheckBox) evt.getSource();
        if (checkBox.isSelected()) {
            tfLPassword.setEchoChar((char) 0); // Show actual characters
        } else {
            tfLPassword.setEchoChar('*'); // Mask characters
        }
    }


    private boolean checkLoginCredentials(String username, String password) {
        try (BufferedReader reader = new BufferedReader(new FileReader("users.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] userData = line.split(",");
                String storedUsername = userData[0];
                String storedPassword = userData[1];
                if (username.equals(storedUsername) && password.equals(storedPassword)) {
                    return true;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel LCpanel;
    private javax.swing.JPanel LLpanel;
    private javax.swing.JLabel LPassword;
    private javax.swing.JPanel LRpanel;
    private javax.swing.JLabel LUsername;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btLsign;
    private javax.swing.JLabel dontHave;
    private javax.swing.JLabel errorMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox seePass;
    private javax.swing.JPasswordField tfLPassword;
    private javax.swing.JTextField tfLUsername;
    // End of variables declaration
}
